### ISSUE TITLE
Config file

### ISSUE THREAD

**Issue by jimpetersson** [rschildmeijer/deft#32]
Probably a good idea to extract some settings (Timeouts etc.) to a separate config-file, instead of hard coded values in code

**Comment by rschildmeijer** [comment]
I'm not sure we will need a config file.  I think its enough to have public apis for timeouts etc. The configuration file is application specific, ie. the client decides if he needs one for his application. (they probably want to have that and then I believe its nice for the client to have one configuration file instead of two (his own + deft cfg file))

comments, thought?

**Comment by rschildmeijer** [comment]
reject; wont fix

**Comment by rschildmeijer** [comment]
.
